/*
 * This file contains a small TypeScript port of the closed-polygon round offset
 * path used by Clipper2's ClipperOffset implementation.
 *
 * Original source: Angus Johnson's Clipper2, CPP/Clipper2Lib/src/clipper.offset.cpp
 * License: Boost Software License 1.0
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

import type { Point } from "../../interface.ts";

const FLOATING_POINT_TOLERANCE = 1e-12;
const CLIPPER_ARC_TOLERANCE_RATIO = 0.002;

export function offsetClosedPolygonRound(points: readonly Point[], distance: number): Point[] {
    const path = removeDuplicateClosingPoint(points);
    if (path.length < 3 || !Number.isFinite(distance)) {
        return path;
    }
    if (Math.abs(distance) < 0.5) {
        return path;
    }

    const area = polygonArea(path);
    if (Math.abs(area) <= FLOATING_POINT_TOLERANCE) {
        return [];
    }

    const groupDelta = area < 0 ? -distance : distance;
    const absDelta = Math.abs(groupDelta);
    if (absDelta <= FLOATING_POINT_TOLERANCE) {
        return path;
    }

    const normals = buildNormals(path);
    const arcTolerance = absDelta * CLIPPER_ARC_TOLERANCE_RATIO;
    const stepsPer360 = Math.min(
        Math.PI / Math.acos(1 - arcTolerance / absDelta),
        absDelta * Math.PI
    );
    const stepSin = Math.sin((2 * Math.PI) / stepsPer360) * (groupDelta < 0 ? -1 : 1);
    const stepCos = Math.cos((2 * Math.PI) / stepsPer360);
    const stepsPerRad = stepsPer360 / (2 * Math.PI);
    const out: Point[] = [];

    for (let j = 0, k = path.length - 1; j < path.length; k = j, j++) {
        offsetRoundPoint(path, normals, j, k, groupDelta, stepSin, stepCos, stepsPerRad, out);
    }

    return trimCollinearPoints(dedupeAdjacentPoints(out));
}

function offsetRoundPoint(
    path: readonly Point[],
    normals: readonly Point[],
    j: number,
    k: number,
    delta: number,
    stepSin: number,
    stepCos: number,
    stepsPerRad: number,
    out: Point[]
) {
    if (samePoint(path[j], path[k])) {
        return;
    }

    let sinA = cross(normals[j], normals[k]);
    const cosA = dot(normals[j], normals[k]);
    sinA = Math.max(-1, Math.min(1, sinA));

    if (Math.abs(delta) <= FLOATING_POINT_TOLERANCE) {
        pushRoundedPoint(out, path[j]);
        return;
    }

    if (cosA > -0.999 && sinA * delta < 0) {
        pushRoundedPoint(out, createConcaveJoinPoint(path, normals, j, k, delta));
        return;
    }

    doRound(path, normals, j, k, Math.atan2(sinA, cosA), delta, stepSin, stepCos, stepsPerRad, out);
}

function createConcaveJoinPoint(
    path: readonly Point[],
    normals: readonly Point[],
    j: number,
    k: number,
    delta: number
): Point {
    const next = (j + 1) % path.length;
    return (
        lineIntersection(
            getPerpendicular(path[k], normals[k], delta),
            getPerpendicular(path[j], normals[k], delta),
            getPerpendicular(path[j], normals[j], delta),
            getPerpendicular(path[next], normals[j], delta)
        ) ?? getPerpendicular(path[j], normals[j], delta)
    );
}

function doRound(
    path: readonly Point[],
    normals: readonly Point[],
    j: number,
    k: number,
    angle: number,
    delta: number,
    stepSin: number,
    stepCos: number,
    stepsPerRad: number,
    out: Point[]
) {
    const point = path[j];
    let offset = {
        x: normals[k].x * delta,
        y: normals[k].y * delta,
    };
    pushRoundedPoint(out, { x: point.x + offset.x, y: point.y + offset.y });

    const steps = Math.ceil(stepsPerRad * Math.abs(angle));
    for (let i = 1; i < steps; i++) {
        offset = {
            x: offset.x * stepCos - stepSin * offset.y,
            y: offset.x * stepSin + offset.y * stepCos,
        };
        pushRoundedPoint(out, { x: point.x + offset.x, y: point.y + offset.y });
    }

    pushRoundedPoint(out, getPerpendicular(point, normals[j], delta));
}

function buildNormals(path: readonly Point[]): Point[] {
    return path.map((point, index) => getUnitNormal(point, path[(index + 1) % path.length]));
}

function getUnitNormal(pointA: Point, pointB: Point): Point {
    const dx = pointB.x - pointA.x;
    const dy = pointB.y - pointA.y;
    const length = Math.hypot(dx, dy);
    if (length <= FLOATING_POINT_TOLERANCE) {
        return { x: 0, y: 0 };
    }
    return {
        x: dy / length,
        y: -dx / length,
    };
}

function getPerpendicular(point: Point, normal: Point, delta: number): Point {
    return {
        x: point.x + normal.x * delta,
        y: point.y + normal.y * delta,
    };
}

function pushRoundedPoint(points: Point[], point: Point) {
    points.push({
        x: Math.round(point.x),
        y: Math.round(point.y),
    });
}

function removeDuplicateClosingPoint(points: readonly Point[]): Point[] {
    const path = points.slice();
    const first = path[0];
    const last = path[path.length - 1];
    if (first && last && samePoint(first, last)) {
        path.pop();
    }
    return path;
}

function dedupeAdjacentPoints(points: Point[]): Point[] {
    const deduped: Point[] = [];
    for (const point of points) {
        const previous = deduped[deduped.length - 1];
        if (previous && samePoint(previous, point)) {
            continue;
        }
        deduped.push(point);
    }
    const first = deduped[0];
    const last = deduped[deduped.length - 1];
    if (first && last && samePoint(first, last)) {
        deduped.pop();
    }
    return deduped;
}

function trimCollinearPoints(points: Point[]): Point[] {
    if (points.length < 3) {
        return points;
    }
    const trimmed: Point[] = [];
    for (let index = 0; index < points.length; index++) {
        const previous = points[(index + points.length - 1) % points.length];
        const current = points[index];
        const next = points[(index + 1) % points.length];
        if (isPointOnSegment(current, previous, next)) {
            continue;
        }
        trimmed.push(current);
    }
    return trimmed;
}

function isPointOnSegment(point: Point, start: Point, end: Point): boolean {
    const area = (end.x - start.x) * (point.y - start.y) - (end.y - start.y) * (point.x - start.x);
    if (Math.abs(area) > 1e-9) {
        return false;
    }
    return (
        point.x >= Math.min(start.x, end.x) &&
        point.x <= Math.max(start.x, end.x) &&
        point.y >= Math.min(start.y, end.y) &&
        point.y <= Math.max(start.y, end.y)
    );
}

function lineIntersection(a1: Point, a2: Point, b1: Point, b2: Point): Point | null {
    const dax = a2.x - a1.x;
    const day = a2.y - a1.y;
    const dbx = b2.x - b1.x;
    const dby = b2.y - b1.y;
    const denominator = dax * dby - day * dbx;
    if (Math.abs(denominator) < FLOATING_POINT_TOLERANCE) {
        return null;
    }

    const t = ((b1.x - a1.x) * dby - (b1.y - a1.y) * dbx) / denominator;
    return {
        x: a1.x + t * dax,
        y: a1.y + t * day,
    };
}

function samePoint(pointA: Point, pointB: Point): boolean {
    return pointA.x === pointB.x && pointA.y === pointB.y;
}

function dot(pointA: Point, pointB: Point): number {
    return pointA.x * pointB.x + pointA.y * pointB.y;
}

function cross(pointA: Point, pointB: Point): number {
    return pointA.y * pointB.x - pointB.y * pointA.x;
}

function polygonArea(points: readonly Point[]): number {
    let area = 0;
    for (let i = 0; i < points.length; i++) {
        const current = points[i];
        const next = points[(i + 1) % points.length];
        area += current.x * next.y - next.x * current.y;
    }
    return area / 2;
}
